// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("metadataexporter")
	ScopeName = "github.com/SigInsight/OtelCollector/exporter/metadataexporter"
)

const (
	TracesStability  = component.StabilityLevelStable
	LogsStability    = component.StabilityLevelStable
	MetricsStability = component.StabilityLevelStable
)
